package io.konekt.components

import io.github.youndie.kompot.UnknownComponent
import io.github.youndie.kompot.decodeKompotComponent
import io.github.youndie.kompot.encodeKompotComponent
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

// WHY THIS TEST HAS THE SHAPE IT DOES.
//
// The registration these components rely on is generated by KSP, and this module's build file
// switches off every per-target ksp task so that generation happens once against the common
// metadata. A disabled task is the classic way to get a green and EMPTY build: nothing fails, no
// registrations are written, and every component silently becomes an UnknownComponent on the wire.
//
// So the exit code of `build` proves nothing about the dictionary, and these assertions are what
// does — per component, not in aggregate. A single "the module is not empty" check would pass on a
// dictionary that had generated one entry out of nine.
class KonektRegistrationTest {
    @Test
    fun `every component is registered under its own wire name`() {
        konektDictionary.forEach { (wireName, component) ->
            val encoded = konektTestJson.encodeKompotComponent(component)
            val type =
                Json
                    .parseToJsonElement(encoded)
                    .jsonObject["type"]
                    ?.jsonPrimitive
                    ?.content

            assertEquals(wireName, type, "${component::class.simpleName} went on the wire as $type")
        }
    }

    @Test
    fun `every component survives a round trip through the generated module`() {
        konektDictionary.forEach { (wireName, component) ->
            val decoded = konektTestJson.decodeKompotComponent(konektTestJson.encodeKompotComponent(component))

            // The UnknownComponent check is not redundant with the equality below — it is the one
            // that names the cause. Without registration the decode succeeds, yields a placeholder,
            // and the equality failure then reads as "expected UsageCounterCardComponent, got
            // UnknownComponent", which is true and says nothing about why.
            assertTrue(
                decoded !is UnknownComponent,
                "$wireName decoded as UnknownComponent — the generated registration does not contain it",
            )
            assertEquals(component, decoded, "$wireName did not survive the round trip")
        }
    }

    @Test
    fun `the dictionary and the published wire-name list are the same set`() {
        // Two lists exist because the JVM-only spec module cannot see a commonTest source set, and
        // two lists drift. This is the seam that stops them: a component added to one and not the
        // other fails here rather than in a schema nobody regenerated.
        assertEquals(konektWireNames, konektDictionary.map { it.first })
    }

    @Test
    fun `a type outside the dictionary degrades instead of throwing`() {
        // Not a hypothetical: the canvas draws this exact case, labelled `esim_transfer_widget`, and
        // the whole additive-dictionary argument rests on it. A future component must cost this
        // client a widget, never the screen.
        val decoded = konektTestJson.decodeKompotComponent("""{"type":"esim_transfer_widget","id":"x"}""")

        assertTrue(decoded is UnknownComponent, "an unfamiliar type must decode, not throw")
        assertEquals("esim_transfer_widget", decoded.originalType)
    }
}
