package io.konekt.screenshots

import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.ui.ImageComposeScene
import androidx.compose.ui.unit.Density
import androidx.compose.ui.use
import io.github.youndie.kompot.LocalKompotRegistry
import io.konekt.client.app.KonektApp
import io.konekt.client.render.konektRegistry
import io.konekt.client.theme.BrandKits
import io.konekt.client.theme.KonektTypography
import kotlinx.coroutines.Dispatchers
import org.jetbrains.skia.EncodedImageFormat
import kotlin.io.path.createDirectories
import kotlin.io.path.writeBytes
import kotlin.test.Test

// THE FRAMES THE README SHOWS, and they are not goldens on purpose.
//
// A golden is photographed on viddik's pinned family, because a frame recorded on a Mac has to
// verify to the pixel on the Linux runner and the product's own faces do not (`B-114` G1, measured at
// 0.07–0.08%). These frames are the same screens on the same recorded trees, drawn in the product's
// own typography — Manrope and Space Grotesk — because a README is read by a person and not compared
// by a machine. They are regenerated by hand, not verified:
//
//     KONEKT_SHOWCASE=true ./gradlew :client:jvmTest --tests '*ShowcaseFrames*'
//
// Without the switch the test does nothing, and says so: a generator that ran on every build would
// rewrite committed pictures on a machine whose fonts nobody chose.
class ShowcaseFrames {
    private data class Frame(
        val file: String,
        val screen: String,
        val brand: String = DEFAULT_BRAND,
        val dark: Boolean = false,
    )

    private val frames =
        listOf(
            Frame("brand-a-home", "home-screen"),
            Frame("brand-a-plans", "plans-screen"),
            Frame("brand-a-plan-detail", "plan-detail-screen"),
            Frame("brand-a-esim-scan", "esim-activate-screen"),
            Frame("brand-a-home-dark", "home-screen", dark = true),
            Frame("brand-a-esim-scan-dark", "esim-activate-screen", dark = true),
            Frame("brand-b-home", "home-screen", brand = "brand-b"),
            Frame("brand-b-plans", "plans-screen", brand = "brand-b"),
            Frame("brand-b-plan-detail", "plan-detail-screen", brand = "brand-b"),
        )

    @Test
    fun `the showcase frames are drawn in the product's own typography`() {
        if (System.getenv("KONEKT_SHOWCASE") != "true") {
            println("ShowcaseFrames: KONEKT_SHOWCASE is not set, drawing nothing")
            return
        }
        // `BrandKits.directory` is `<root>/server/src/main/resources/themes`; the frames go beside the
        // documentation at the root, where the README reads them from.
        val root =
            generateSequence(BrandKits.directory) { it.parent }
                .first { it.resolve("settings.gradle.kts").toFile().exists() }
        val out = root.resolve("docs/screenshots").createDirectories()

        frames.forEach { frame ->
            val kit = BrandKits.kits().getValue(frame.brand)
            ImageComposeScene(
                width = APP_WIDTH * SCALE,
                height = APP_HEIGHT * SCALE,
                density = Density(SCALE.toFloat()),
                coroutineContext = Dispatchers.Unconfined,
            ).use { scene ->
                scene.setContent {
                    CompositionLocalProvider(LocalKompotRegistry provides konektRegistry()) {
                        KonektApp(
                            screens = Recorded(frame.screen),
                            address = "/recorded/${frame.screen}",
                            topic = "showcase",
                            darkMode = frame.dark,
                            theme = kit,
                            typography = KonektTypography.material,
                        )
                    }
                }
                // The recorded tree arrives through a suspend fetch; frames are rendered until
                // nothing is left to draw, bounded so a screen that never settles cannot hang this.
                var time = 0L
                var image = scene.render(time)
                var passes = 0
                while (scene.hasInvalidations() && passes < 100) {
                    time += 16_000_000L
                    image = scene.render(time)
                    passes += 1
                }
                val png = requireNotNull(image.encodeToData(EncodedImageFormat.PNG)) { "png encoding failed" }
                out.resolve("${frame.file}.png").writeBytes(png.bytes)
                println("ShowcaseFrames: wrote ${frame.file}.png after ${passes + 1} render passes")
            }
        }
    }

    private companion object {
        const val SCALE = 2
    }
}
